service: pz-trello-praise

provider:
  name: openwhisk
  runtime: nodejs:10

functions:
  hello:
    handler: handler.hello

plugins:
  - serverless-openwhisk

resources:
  packages:
    wskCommon:
      binding: /whisk.system/slack
      parameters:
        url: @SLACK_WEBHOOK_URL@
        username: @SLACK_APP_USER@
        channel: @SLACK_CHANNEL@
