service: pz-trello-praise

provider:
  name: openwhisk
  runtime: nodejs:10

functions:
  hello:
    name: "pzPraiser/main"
    handler: handler.main
  pzPraiserSeq:
    name: "pzPraiser/praiserSeq"
    sequence:
      - /_/pzPraiser/main
      - /_/wskCommon/post

plugins:
  - serverless-openwhisk

resources:
  packages:
    wskCommon:
      binding: /whisk.system/slack
      parameters:
        url: @SLACK_WEBHOOK_URL@
        username: @SLACK_APP_USER@
        channel: @SLACK_CHANNEL@
